# base image
FROM python:3.6.5-alpine

# install dependencies
RUN apk update && \
    apk add --virtual build-deps gcc python-dev musl-dev && \
    apk add postgresql-dev && \
    apk add netcat-openbsd

# set working directory
WORKDIR /usr/src/app

# add app
COPY . /usr/src/app

# add and install requirements
RUN pip install -r requirements.txt

# run server
CMD ["/usr/src/app/entrypoint.sh"]
